version: "3.9"

services:

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    networks:
      - db_network


  web:
    build: .
    command: gunicorn MCJCTF.wsgi -b 0.0.0.0:8000
    volumes:
      - .:/code
      - static_volume:/code/static  # <-- bind the static volume
      - media_volume:/code/media

    env_file:
      - .env

    links:
      - db:db
    depends_on:
      - db
    networks:
      - nginx_network
      - db_network

  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - static_volume:/code/static  # <-- bind the static volume
      - media_volume:/code/media
    depends_on:
      - web
    networks:  # <-- here
      - nginx_network

volumes:
  postgres_data:
  static_volume:  # <-- declare the static volume
  media_volume:  # <-- declare the media volume



networks:
  db_network:
    driver: bridge

  nginx_network:
    driver: bridge
