version: "3.9"

services:

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASS=${POSTGRES_PWD}
      - POSTGRES_DB=${POSTGRES_NAME}
      - POSTGRES_PORT=5432


    networks:
      service-network:
        aliases:
          - db

  web:
    build: .
    command: gunicorn MCJCTF.wsgi -b 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    environment:
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - DJANGO_DEBUG=${DJANGO_DEBUG}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASS=${POSTGRES_PWD}
      - POSTGRES_DB=${POSTGRES_NAME}

    links:
      - db:db
    depends_on:
      - db
    networks:
      service-network:
        aliases:
          - web

volumes:
  postgres_data:


networks:
  service-network:
    name: service-network
    driver: bridge
