# Generated by Django 4.2.1 on 2023-06-01 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='head',
            name='description',
            field=models.TextField(),
        ),
    ]
