# Generated by Django 4.1.7 on 2023-05-23 17:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scoreboards", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scoreboardteam",
            name="score",
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="scoreboarduser",
            name="score",
            field=models.BigIntegerField(null=True),
        ),
    ]
