# Generated by Django 4.1.7 on 2023-05-23 17:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scoreboards", "0002_alter_scoreboardteam_score_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scoreboardteam",
            name="score",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="scoreboarduser",
            name="score",
            field=models.BigIntegerField(default=0),
        ),
    ]
