# Generated by Django 4.1.7 on 2023-05-27 16:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('flag', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.TextField()),
                ('challenge_file', models.FileField(blank=True, upload_to='challenges/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('point', models.IntegerField()),
            ],
        ),
    ]
