# Generated by Django 4.1.7 on 2023-05-22 11:48

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Challenge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("challenge_file", models.FileField(upload_to="challenges/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("point", models.IntegerField()),
            ],
        ),
    ]
