# Generated by Django 4.1.7 on 2023-05-22 12:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("challenges", "0002_alter_challenge_challenge_file_alter_challenge_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="challenge",
            name="flag",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
