# Generated by Django 4.1.7 on 2023-05-22 12:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("challenges", "0003_challenge_flag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="challenge",
            name="flag",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
