# Generated by Django 4.1.7 on 2023-05-23 11:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("challenges", "0004_alter_challenge_flag"),
    ]

    operations = [
        migrations.AddField(
            model_name="challenge",
            name="category",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="flag",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
